#define ONESHOT_TAP_TOGGLE 3

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "Bwv6O/v6ypqr"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 4

#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 5
#define AUTOMOUSE_THRESHOLD 20
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

